apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce # Only one pod can mount this PVC at a time
  resources:
    requests:
      storage: 10Gi # Request 10 GiB of storage